SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3
PLAYER_INVINCIBILITY_TIME = 2.0

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Asteroid scores based on size
ASTEROID_SCORE_LARGE = 20    # radius = 60
ASTEROID_SCORE_MEDIUM = 50   # radius = 40
ASTEROID_SCORE_SMALL = 100   # radius = 20

SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SHOT_LIFETIME = 1.5

# Wave system
WAVE_START_ASTEROIDS = 4
WAVE_ASTEROID_INCREMENT = 1
WAVE_PAUSE_TIME = 2.0
WAVE_SPEED_MULTIPLIER = 1.1

# UFO settings
UFO_SPAWN_MIN_TIME = 20
UFO_SPAWN_MAX_TIME = 30
UFO_LARGE_RADIUS = 30
UFO_SMALL_RADIUS = 15
UFO_LARGE_SPEED = 80
UFO_SMALL_SPEED = 120
UFO_LARGE_SCORE = 200
UFO_SMALL_SCORE = 1000
UFO_SHOOT_COOLDOWN = 1.5

# Power-up settings
POWERUP_RADIUS = 15
POWERUP_DURATION = 10.0
POWERUP_SHIELD_DURATION = 5.0
POWERUP_RAPID_FIRE_MULTIPLIER = 3
POWERUP_DROP_CHANCE = 0.1

# Physics
PLAYER_THRUST = 300
PLAYER_DRAG = 0.98
PLAYER_MAX_SPEED = 400

# Particle settings
PARTICLE_LIFETIME = 0.5
PARTICLE_COUNT_EXPLOSION = 12
PARTICLE_COUNT_THRUST = 3
PARTICLE_SPEED = 150

# Colors
COLOR_WHITE = "white"
COLOR_RED = "red"
COLOR_BLUE = (100, 100, 255)
COLOR_YELLOW = (255, 255, 100)
COLOR_ORANGE = (255, 165, 0)
COLOR_GREEN = (100, 255, 100)

# Game states
STATE_MENU = "menu"
STATE_PLAYING = "playing"
STATE_PAUSED = "paused"
STATE_GAME_OVER = "game_over"
STATE_WAVE_PAUSE = "wave_pause"
